apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "davidacr.azurecr.io": {
          "username": "ZGF2aWRhY3IuYXp1cmVjci5pbw==", 
          "password": "eEliNWxwb1dvWmdaRm9RNHhaV2pjNmZlQzJpdXZtMHR0YVpsU1dTU0tpK0FDUkNsWFVFWA==",
          "email": "david.ramon578@comunidadunir.net"
        }
      }
    }
