---
- name: Descargar y subir imagenes redis, azure_vote_front a mi Azure ACR
  hosts: miHost
  become: yes
  vars_files:
    - variables.yml

  tasks:
    - name: Iniciar sesi칩n en ACR
      containers.podman.podman_login:
        registry: "{{ mi_usuario }}"
        username: "{{ mi_acr }}"
        password: "{{ mi_contrasenya }}"
      register: podman_login
      failed_when: podman_login.failed 

    - name: Descargar im치genes desde Docker Hub
      containers.podman.podman_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag | default('latest') }}"
        state: present
        pull: yes
      loop:
        - { name: "docker.io/library/redis", tag: "latest" }
        - { name: "docker.io/freelancer08/azure-vote-front", tag: "latest" }

    - name: Etiquetar im치genes descargadas para ACR
      containers.podman.podman_tag:
        image: "{{ item.name }}"
        target_names: "{{ mi_usuario }}/{{ item.name }}:{{ tagged_image }}"
      loop:
        - { name: "redis" }
        - { name: "azure-vote-front" }

    - name: Subir im치genes a ACR
      containers.podman.podman_image:
        name: "{{ mi_usuario }}/{{ item.name }}"
        tag: "{{ tagged_image }}"
        push: yes
      loop:
        - { name: "redis" }
        - { name: "azure-vote-front" }
