---
- name: Descargar y subir imagen nginx a Azure ACR
  hosts: miHost
  become: yes
  vars_files:
    - variables.yml

  tasks:
    - name: Iniciar sesi칩n en ACR
      containers.podman.podman_login:
        registry: "{{ mi_usuario }}"
        username: "{{ mi_acr }}"
        password: "{{ mi_contrasenya }}"
      register: podman_login
      failed_when: podman_login.failed 

    - name: Descargar im치genes desde Docker Hub
      containers.podman.podman_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag | default('latest') }}"
        state: present
        pull: yes
      loop:
        - { name: "docker.io/nginx", tag: "latest"}

    - name: Etiquetar im치genes descargadas para ACR
      containers.podman.podman_tag:
        image: "{{ item.name }}"
        target_names: "{{ mi_usuario }}/{{ item.name }}:{{ tagged_image }}"
      loop:
        - { name: "nginx" }

    - name: Subir im치genes a ACR
      containers.podman.podman_image:
        name: "{{ mi_usuario }}/{{ item.name }}"
        tag: "{{ tagged_image }}"
        push: yes
      loop:
        - { name: "nginx" }

    - name: Ejecutar el contenedor nginx desde ACR
      containers.podman.podman_container:
        name: nginx_container
        image: "{{ mi_usuario }}/nginx:{{ tagged_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
